// Auto-generated file - do not edit manually
// Generated from src/resources/rules/ directory

export const RESOURCES_RULES = {
  'groundzero.md': "---\ndescription:\nglobs:\nalwaysApply: true\n---\n\n**INSTRUCTIONS: Always search and read through any relevant guidelines under the /ai directory before starting any task**\n\n# The /ai directory\n\n- **Description**: A /ai directory contains information for the directory of the code it is placed in. Information is provided in the form of markdown files. Follow the given information within these markdown files to construct and update the code for it's given scope.\n- **Scope**: A codebase may have multiple /ai directories, each scoped to their respective parent directories and children.\n  - Ex: /project/foo/bar/ai contains information for the set of code and child directories under /project/foo/bar.\n  - Ex: /project/foo/ai contains information for the set of code and child directories under /project/foo, including and applied to /project/foo/bar.\n- **Purpose**: The purpose of the provided information within the /ai directory is to ensure the maintainability, consistency, and scalability of the given software.\n\n**REMEMBER: Always search and read through any relevant guidelines under the /ai directory before starting any task**",
  'ai.md': "---\nglobs: ai/**\nalwaysApply: false\n---\n\n# Steps to update /ai documentation\n\n1. Read relevant markdown files carefully and note existing information.\n2. Determine if new markdown files are required for clean separation of domain/concerns, if so, create.\n3. Make very concise and efficient updates, do NOT be verbose.\n4. Ensure information you add are clear and to the point and NOT verbose.\n5. Do not make any changes or updates that are not specifically mentioned.\n6. Review your implementation and refactor and/or split markdown files whenever necessary.\n7. Ensure each markdown file compact and concise in information, less than 300 lines.\n8. Clean up information if necessary.\n\n## DO:\n- Make minimal, focused changes\n- Use short, direct explanations\n- Keep code examples brief and essential only\n- Remove unnecessary detail\n- Focus on core requirements only\n\n## DO NOT:\n- Add extensive code examples\n- Provide long explanations\n- Include verbose documentation\n- Add unnecessary context\n- Make comprehensive overhauls when simple updates suffice\n\n**Remember: Following explicit verbosity constraints is more important than being thorough.**",
} as const;

export type ResourceRuleFile = keyof typeof RESOURCES_RULES;
export type Platform = 'cursor' | 'general';
